@herokuBaseUrl=https://chaos-board-backend.herokuapp.com/api/board
@baseUrl=http://localhost:3005/api/board
@boardId=5ae9d453b0f47c69442dd3b9
@deleteBoardId=5b0541fd4c27247d5410d9a2
@deleteContainerId=5af1992e7f265c996047a471

GET {{baseUrl}}

###

GET {{baseUrl}}/{{boardId}}

###

DELETE {{baseUrl}}/{{boardId}}/{{deleteContainerId}}

###

DELETE {{baseUrl}}/{{deleteBoardId}}

###

POST {{herokuBaseUrl}}
Content-Type: application/json

{
  "title": "Chaos board",
  "description": "description not used"
}

###

PUT {{baseUrl}}/{{boardId}}
Content-Type: application/json

{
    "title": "updated title",
    "description": "something else than first"
}