
POST http://localhost:3005/api/board
Content-Type: application/json

{
  "title": "testing",
  "description": "test description",
  "boardId": "9e2a2af0-49fc-11e8-ba20-e59ca261772f",
  "boardTitle": "testing board",
  "boardDescription": "yes testing it"
}

###

PUT http://localhost:3005/api/board/5ae2ec0403601a531446b29a
Content-Type: application/json

{
  "title": "updated title"
}
###

GET http://localhost:3005/api/board

###

GET http://localhost:3005/api/board/9e2a2af0-49fc-11e8-ba20-e59ca261772f