
@baseUrl=http://localhost:3005/api/board
@boardId=5ae97f3d4964c83b1006f55d
@deleteBoardId=5ae97e17e7d5936ddc793986

GET {{baseUrl}}

###

GET {{baseUrl}}/{{boardId}}

###

DELETE {{baseUrl}}/{{deleteBoardId}}

###

POST {{baseUrl}}
Content-Type: application/json

{
  "title": "testing2",
  "description": "test description"
}

###

PUT {{baseUrl}}/{{boardId}}
Content-Type: application/json

{
    "title": "updated title",
    "description": "something else than first"
}