
@baseUrl=http://localhost:3005/api/board
@boardId=5ae97f3d4964c83b1006f55d
@deleteBoardId=5ae97f3d4964c83b1006f55d

GET {{baseUrl}}

###

GET {{baseUrl}}/{{boardId}}

###

DELETE {{baseUrl}}/{{deleteBoardId}}

###

POST {{baseUrl}}
Content-Type: application/json

{
  "title": "test board",
  "description": "description not used"
}

###

PUT {{baseUrl}}/{{boardId}}
Content-Type: application/json

{
    "title": "updated title",
    "description": "something else than first"
}