
@baseUrl=http://localhost:3005/api/card
@containerId=5ae70eddb52b800588b2e7c5
@cardId=5ae714ed490fa84734900534

POST {{baseUrl}}/{{containerId}}
Content-Type: application/json

{
  "title": "yes it works",
  "text": "at last",
  "position": 2
}

###

DELETE {{baseUrl}}/{{containerId}}/{{cardId}}

###

PUT {{baseUrl}}/{{containerId}}/{{cardId}}
Content-Type: application/json

{
  "title": "editing is ok"
}