
@baseUrl=http://localhost:3005/api/card
@containerId=5ae97f4c4964c83b1006f55e
@cardId=5ae714ed490fa84734900534

GET {{baseUrl}}

###

POST {{baseUrl}}/{{containerId}}
Content-Type: application/json

{
  "title": "yes it works",
  "text": "at last",
  "position": 2
}

###

DELETE {{baseUrl}}/{{containerId}}/{{cardId}}

###

PUT {{baseUrl}}/{{containerId}}/{{cardId}}
Content-Type: application/json

{
  "title": "editing is ok"
}