
@baseUrl=http://localhost:3005/api/container
@containerId=5ae70eddb52b800588b2e7c5
@deleteContainerId=5ae96043fef97d6ff83415a5
@boardId=5ae97f3d4964c83b1006f55d

GET {{baseUrl}}

###

GET {{baseUrl}}/{{containerId}}

###

DELETE {{baseUrl}}/{{deleteContainerId}}

###

POST {{baseUrl}}/{{boardId}}
Content-Type: application/json

{
  "title": "test container title",
  "description": "container description",
  "position": 0
}

###

PUT {{baseUrl}}/{{boardId}}/{{containerId}}
Content-Type: application/json

{
    "title": "updated container title"
}