
@baseUrl=http://localhost:3005/api/container
@containerId=5ae70eddb52b800588b2e7c5
@deleteContainerId=5ae96043fef97d6ff83415a5
@boardId=5ae9d453b0f47c69442dd3b9

GET {{baseUrl}}

###

GET {{baseUrl}}/{{containerId}}

###

DELETE {{baseUrl}}/{{deleteContainerId}}

###

POST {{baseUrl}}/{{boardId}}
Content-Type: application/json

{
  "title": "fourth",
  "description": "description not used",
  "position": 3
}

###

PUT {{baseUrl}}/{{boardId}}/{{containerId}}
Content-Type: application/json

{
    "title": "updated container title"
}