@baseUrl=http://localhost:3005/api/user/

@loginUrl=http://localhost:3005/api/login

@userId=5afb052874131984ccb7a017

GET http://localhost:3005/api/login
###
GET {{baseUrl}}/{{userId}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbndpbiIsImlkIjoiNWFmYjA1Mjg3NDEzMTk4NGNjYjdhMDE3IiwiaWF0IjoxNTI2NDY0NTM2fQ.vRKGY1AeY0OjgU5SKwGJHNVx1xMS9TLav035cmRxxbA
###
GET {{baseUrl}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbndpbiIsImlkIjoiNWFmYjA1Mjg3NDEzMTk4NGNjYjdhMDE3IiwiaWF0IjoxNTI2NDY0NTM2fQ.vRKGY1AeY0OjgU5SKwGJHNVx1xMS9TLav035cmRxxbA
###
POST {{baseUrl}}
Content-Type: application/json

{
  "username": "winwin",
  "name": "reality",
  "password": "loselose"
}
###
POST {{loginUrl}}
Content-Type: application/json

{
  "username": "winwin",
  "password": "loselose"
}
###
DELETE {{baseUrl}}/5afafee6a82a2f979889e531